name: School FAQ CI/CD
run-name: ${{ github.actor }} 🚀

on:
  push:
    branches:
      - main
      - UserLogin

jobs:
  FrontEndCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/schoolfaq

      - name: Run tests
        run: npm run test
        working-directory: ./frontend/schoolfaq

  # Backend CI for Flask
  BackEndCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        working-directory: ./backend

      # - name: Run tests
      #   run: |
      #     source .venv/bin/activate
      #     pytest
      #   working-directory: ./backend

  # Frontend CD for Next.js (Deployment)
  FrontEndCD:
    runs-on: ubuntu-latest
    needs: FrontEndCI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/schoolfaq

      - name: Build for production
        run: npm run build
        working-directory: ./frontend/schoolfaq

      # - name: Deploy
      #   run: echo "Deploying Next.js application..."
        

  # Backend CD for Flask (Deployment)
  BackEndCD:
    runs-on: ubuntu-latest
    needs: BackEndCI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        working-directory: ./backend

      # - name: Deploy Flask app
      #   run: echo "Deploying Flask application..."
        
